CREATE TABLE TRANSACTION_SUMMARY AS (
SELECT MERCHANT_ID
, COUNT(DISTINCT ORDER_ID) AS TTL_ORDERS
, COUNT(DISTINCT CASE WHEN fulfillment_shipped_at > item_ship_by_date THEN ORDER_ID ELSE NULL END) TTL_ORDERS_LATE
, COUNT(DISTINCT CASE WHEN item_discount > 0 THEN ORDER_ID ELSE NULL END) TTL_ORDERS_DISCOUNTED
, SUM(item_selling_price) as item_selling_price
, SUM(CASE WHEN fulfillment_shipped_at > item_ship_by_date THEN item_selling_price ELSE 0 END) ITEM_SELLING_PRICE_LATE
FROM TRANSACTIONS
WHERE fulfillment_shipped_at <> 'null'
GROUP BY 1);

CREATE TABLE RETURN_CANCELLED_SUMMARY AS (
SELECT MERCHANT_ID
, SUM(CANCEL_NUM) AS CANCEL_NUM
, SUM(RETURN_NUM) AS RETURN_NUM
FROM ReturnedCancelledData
GROUP BY 1);

CREATE TABLE MERCHANT_SUMMARY AS (
SELECT A.*, B.CANCEL_NUM, B.RETURN_NUM
FROM TRANSACTION_SUMMARY A
LEFT JOIN RETURN_CANCELLED_SUMMARY B
ON A.MERCHANT_ID = B.MERCHANT_ID);

CREATE TABLE MERCHANT_CREDIT_SCORE AS (
SELECT A.MERCHANT_ID
, CASE
	WHEN CREDIT_SCORE <=500 THEN 500
	ELSE CREDIT_SCORE
END AS CREDIT_SCORE_FINAL
FROM (
SELECT MERCHANT_ID
, CASE 
	WHEN CANCEL_NUM > TTL_ORDERS_LATE AND RETURN_NUM > TTL_ORDERS_LATE THEN 1000 - ((CANCEL_NUM+RETURN_NUM)/2)/TTL_ORDERS*100
	WHEN CANCEL_NUM > TTL_ORDERS_LATE THEN 1000 - (CANCEL_NUM - TTL_ORDERS_LATE)/TTL_ORDERS*100
	WHEN RETURN_NUM > TTL_ORDERS_LATE THEN 1000 - (RETURN_NUM - TTL_ORDERS_LATE)/TTL_ORDERS*100
	WHEN TTL_ORDERS_DISCOUNTED > 0 THEN 1000 - (TTL_ORDERS_LATE/TTL_ORDERS*100)	
	WHEN ITEM_SELLING_PRICE_LATE > 0 THEN 1000 - (ITEM_SELLING_PRICE_LATE/ITEM_SELLING_PRICE)*100
	ELSE 1000
END AS CREDIT_SCORE
FROM MERCHANT_SUMMARY) A
);
